/*
 * parity.test.cjs — proves the JavaScript parser in web/rubric.js reproduces,
 * byte-for-byte, the golden output the REFERENCE Python parser produced for
 * every case in tests/conformance.
 *
 * The goldens are generated by `python tests/conformance/build.py`. This test
 * reads the SAME input files the Python conformance test reads, so a divergence
 * anywhere — a regex that behaves differently, a YAML edge case, a chomping
 * rule — turns this red instead of silently shipping a playground that grades
 * questions differently from the CLI.
 *
 *     node web/test/parity.test.cjs
 *
 * Exits 0 on full parity, 1 (with a diff) otherwise. No dependencies.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const Rubric = require("../rubric.js");

const REPO = path.resolve(__dirname, "..", "..");
const CASES_DIR = path.join(REPO, "tests", "conformance", "cases");
const EXPECTED_DIR = path.join(REPO, "tests", "conformance", "expected");

// Canonical stringify: recursively sort object keys so comparison is
// order-independent, matching the Python side's sort_keys=True.
function canonical(value) {
  if (Array.isArray(value)) {
    return "[" + value.map(canonical).join(",") + "]";
  }
  if (value && typeof value === "object") {
    const keys = Object.keys(value).sort();
    return (
      "{" +
      keys.map((k) => JSON.stringify(k) + ":" + canonical(value[k])).join(",") +
      "}"
    );
  }
  return JSON.stringify(value);
}

// Re-shape a JS ParseResult into the language-neutral payload the goldens use.
function serialize(result) {
  const diag = (d) => ({ line: d.line, message: d.message, severity: d.severity });
  return {
    success: result.success,
    data: result.data === undefined ? null : result.data,
    errors: result.errors.map(diag),
    warnings: result.warnings.map(diag),
  };
}

function main() {
  if (!fs.existsSync(EXPECTED_DIR)) {
    console.error(
      "No golden fixtures found. Run: python tests/conformance/build.py"
    );
    process.exit(2);
  }

  const goldens = fs
    .readdirSync(EXPECTED_DIR)
    .filter((f) => f.endsWith(".json"))
    .sort();

  if (goldens.length === 0) {
    console.error("No .json goldens in " + EXPECTED_DIR);
    process.exit(2);
  }

  let passed = 0;
  const failures = [];

  for (const golden of goldens) {
    const name = golden.replace(/\.json$/, "");
    const casePath = path.join(CASES_DIR, name + ".md");
    if (!fs.existsSync(casePath)) {
      failures.push({ name, why: "missing case file " + casePath });
      continue;
    }
    const dsl = fs.readFileSync(casePath, "utf-8");
    const expected = JSON.parse(fs.readFileSync(path.join(EXPECTED_DIR, golden), "utf-8"));

    const actual = serialize(Rubric.parse(dsl));

    const a = canonical(actual);
    const e = canonical(expected);
    if (a === e) {
      passed += 1;
    } else {
      failures.push({
        name,
        why: "output differs from golden",
        expected: JSON.stringify(expected, null, 2),
        actual: JSON.stringify(actual, null, 2),
      });
    }
  }

  console.log(`Parity: ${passed}/${goldens.length} cases match the Python reference.`);

  if (failures.length) {
    console.error("\n" + failures.length + " FAILED:\n");
    for (const f of failures) {
      console.error("  ✗ " + f.name + " — " + f.why);
      if (f.expected) {
        console.error("    --- expected (Python) ---");
        console.error(indent(f.expected, "    "));
        console.error("    --- actual (JS) ---");
        console.error(indent(f.actual, "    "));
      }
    }
    process.exit(1);
  }

  console.log("All cases match. The JS port is in lockstep with the reference parser.");
}

function indent(s, pad) {
  return s
    .split("\n")
    .map((l) => pad + l)
    .join("\n");
}

main();
