/*
 * build_examples.cjs — inline every example bank into web/examples.bundle.js.
 *
 * The playground is fully static and must run from file:// as well as from a
 * static host, so it cannot fetch the example .md files at runtime (file://
 * fetch is blocked, and we want zero network dependency). Instead this script
 * walks examples/, resolves each manifest's question files IN MANIFEST ORDER,
 * reads their text, and emits a single classic script that assigns the whole
 * corpus to globalThis.RUBRIC_EXAMPLES.
 *
 * Re-run whenever the example banks change:
 *     node web/build_examples.cjs
 */
"use strict";

const fs = require("fs");
const path = require("path");

const REPO = path.resolve(__dirname, "..");
const EXAMPLES = path.join(REPO, "examples");
const OUT = path.join(__dirname, "examples.bundle.js");

// Featured first (it showcases both differentiators: per-choice rationale AND a
// deliberately incomplete blueprint). Everything else follows alphabetically.
const PRIORITY = ["comptia-security-plus"];

function findManifests(dir) {
  const found = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...findManifests(full));
    } else if (entry.name === "manifest.json") {
      found.push(full);
    }
  }
  return found;
}

function loadBundle(manifestPath) {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
  const root = path.dirname(manifestPath);
  const rel = Array.isArray(manifest.question_files) ? manifest.question_files : [];

  const questions = [];
  const missing = [];
  for (const qrel of rel) {
    const qpath = path.join(root, qrel);
    if (!fs.existsSync(qpath)) {
      missing.push(qrel);
      continue;
    }
    questions.push({ file: qrel, text: fs.readFileSync(qpath, "utf-8") });
  }
  if (missing.length) {
    throw new Error(
      `${manifestPath}: ${missing.length} referenced question file(s) missing, ` +
        `e.g. ${missing[0]}`
    );
  }

  const cert = manifest.certification || {};
  const vendor = manifest.vendor || {};
  const id =
    cert.slug ||
    manifest.slug ||
    path.relative(EXAMPLES, root).replace(/[\\/]/g, "-");

  return {
    id,
    title: cert.name || vendor.name || id,
    vendor: vendor.name || "",
    path: path.relative(REPO, root).replace(/\\/g, "/"),
    manifest,
    questions,
  };
}

function main() {
  if (!fs.existsSync(EXAMPLES)) {
    console.error("No examples/ directory found at " + EXAMPLES);
    process.exit(2);
  }

  const bundles = findManifests(EXAMPLES).map(loadBundle);

  bundles.sort((a, b) => {
    const pa = PRIORITY.indexOf(a.id);
    const pb = PRIORITY.indexOf(b.id);
    if (pa !== -1 || pb !== -1) {
      return (pa === -1 ? 99 : pa) - (pb === -1 ? 99 : pb);
    }
    return a.title.localeCompare(b.title);
  });

  const totalQ = bundles.reduce((n, b) => n + b.questions.length, 0);
  const payload = JSON.stringify(bundles);

  const banner =
    "/* AUTO-GENERATED by web/build_examples.cjs — do not edit by hand.\n" +
    ` * ${bundles.length} bundle(s), ${totalQ} question(s). Regenerate with:\n` +
    " *     node web/build_examples.cjs\n" +
    " */\n";
  const body =
    banner +
    "(function (root) {\n" +
    "  root.RUBRIC_EXAMPLES = " +
    payload +
    ";\n" +
    "})(typeof globalThis !== \"undefined\" ? globalThis : this);\n";

  fs.writeFileSync(OUT, body, { encoding: "utf-8" });

  const kb = (Buffer.byteLength(body, "utf-8") / 1024).toFixed(0);
  console.log(
    `Wrote ${path.relative(REPO, OUT).replace(/\\/g, "/")} — ` +
      `${bundles.length} bundles, ${totalQ} questions, ${kb} KB.`
  );
  for (const b of bundles) {
    console.log(`  • ${b.id.padEnd(26)} ${b.questions.length} q`);
  }
}

main();
